
package com.redsun.bos.ws.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WallbillServiceService", targetNamespace = "http://impl.ws.bos.redsun.com/", wsdlLocation = "http://192.168.94.85:8080/redsun_web/ws/waybill?wsdl")
public class WallbillServiceService
    extends Service
{

    private final static URL WALLBILLSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException WALLBILLSERVICESERVICE_EXCEPTION;
    private final static QName WALLBILLSERVICESERVICE_QNAME = new QName("http://impl.ws.bos.redsun.com/", "WallbillServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.94.85:8080/redsun_web/ws/waybill?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WALLBILLSERVICESERVICE_WSDL_LOCATION = url;
        WALLBILLSERVICESERVICE_EXCEPTION = e;
    }

    public WallbillServiceService() {
        super(__getWsdlLocation(), WALLBILLSERVICESERVICE_QNAME);
    }

    public WallbillServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WALLBILLSERVICESERVICE_QNAME, features);
    }

    public WallbillServiceService(URL wsdlLocation) {
        super(wsdlLocation, WALLBILLSERVICESERVICE_QNAME);
    }

    public WallbillServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WALLBILLSERVICESERVICE_QNAME, features);
    }

    public WallbillServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WallbillServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IWallbillService
     */
    @WebEndpoint(name = "WallbillServicePort")
    public IWallbillService getWallbillServicePort() {
        return super.getPort(new QName("http://impl.ws.bos.redsun.com/", "WallbillServicePort"), IWallbillService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IWallbillService
     */
    @WebEndpoint(name = "WallbillServicePort")
    public IWallbillService getWallbillServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.ws.bos.redsun.com/", "WallbillServicePort"), IWallbillService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WALLBILLSERVICESERVICE_EXCEPTION!= null) {
            throw WALLBILLSERVICESERVICE_EXCEPTION;
        }
        return WALLBILLSERVICESERVICE_WSDL_LOCATION;
    }

}
